export const GAME_EVENTS = {
  USER: {
    CONNECTED: "user:connected",
    JOINED: "user:joined",
    DISCONNECTED: "user:disconnected",
  },
  ROOM: {
    CREATE: "room:create",
    JOIN: "room:join",
    LEAVE: "room:leave",
    LIST: "room:list",
    CREATED: "room:created",
    JOINED: "room:joined",
    LEFT: "room:left",
    UPDATED: "room:updated",
    FULL: "room:full",
    NOT_FOUND: "room:not_found",
    STARTED: "room:started",
    ENDED: "room:ended",
  },
  PARTY: {
    MEMBER_JOINED: "party:member_joined",
    MEMBER_LEFT: "party:member_left",
    LEADER_CHANGED: "party:leader_changed",
    READY_STATE: "party:ready_state",
    ALL_READY: "party:all_ready",
  },
  CHAT: {
    MESSAGE: "chat:message",
    LOBBY_MESSAGE: "chat:lobby_message",
    GAME_MESSAGE: "chat:game_message",
    SYSTEM_MESSAGE: "chat:system_message",
  },
  PLAYER: {
    SPAWN: "player:spawn",
    POSITION: "player:position",
    ROTATION: "player:rotation",
    STATUS: "player:status",
    HEALTH: "player:health",
    DEATH: "player:death",
    RESPAWN: "player:respawn",
    READY: "player:ready",
    NOT_READY: "player:not_ready",
  },
  WEAPON: {
    SHOOT: "weapon:shoot",
    RELOAD: "weapon:reload",
    SWITCH: "weapon:switch",
    PICKUP: "weapon:pickup",
    DROP: "weapon:drop",
  },
  COMBAT: {
    HIT: "combat:hit",
    DAMAGE: "combat:damage",
    KILL: "combat:kill",
    EXPLOSION: "combat:explosion",
  },
  WORLD: {
    DEMON_SPAWN: "world:demon:spawn",
    DEMON_DEATH: "world:demon:death",
    DEMON_UPDATE: "world:demon:update",
    WAVE_START: "world:wave:start",
    WAVE_COMPLETE: "world:wave:complete",
    PICKUP_SPAWN: "world:pickup:spawn",
    PICKUP_COLLECT: "world:pickup:collect",
    DOOR_OPEN: "world:door:open",
    DOOR_CLOSE: "world:door:close",
    ROOM_ENTER: "world:room:enter",
    ROOM_EXIT: "world:room:exit",
  },
  GAME: {
    START: "game:start",
    END: "game:end",
    PAUSE: "game:pause",
    RESUME: "game:resume",
    STATE_UPDATE: "game:state_update",
  },
} as const;
